### ISSUE TITLE
MoveFacet goes in out of gas

### ISSUE THREAD

**Issue by lterrac** [darkforest-eth/eth#6]
Hi everyone, I am currently trying to deploy the smart contract on Ganache for local development but, when it comes to `DFMoveFacet` the transaction goes in out of gas. TBH, I am not using hardhat but only the web3 library ( it is for a university project and we are not allowed to use truffle and hardhat). I want to ask you guys if you handle the `DFMoveFacet` in some particular ways to deploy it?

Thank you in advance

**Comment by phated** [comment]
It's an expensive function, especially if you are dealing with a bunch of artifacts or something. You can force more gas limits.

**Comment by lterrac** [comment]
Yes I enforced more gas and it worked, thanks a lot
